version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      - NODE_ENV: development # CircleCI needs devDeps

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # build the extension if required
      - run: yarn build

      # Run unit tests
      - run: yarn test

      # Run end to end
      - run: yarn e2e

      # Publish new version to chrome webstore
      - run: yarn semantic-release || true
