version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.12.0-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

          # fall back to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install your dependencies
      - run: yarn install

      # - run:
      #     name: Workaround for GoogleChrome/puppeteer#290
      #     command: 'sh .circleci/install-puppeteer.sh'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build the extension if required
      # Run unit tests
      # - run: yarn test

      # Run end to end
      - run: yarn e2e
