// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var list = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var listA = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var listB = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

console.log("list(int)");

console.log(list);

console.log(" ");

var nestedList_001 = /* :: */[
  listA,
  /* :: */[
    listB,
    /* [] */0
  ]
];

var nestedList = /* :: */[
  list,
  nestedList_001
];

console.log("list(list(int))");

console.log(nestedList);

console.log(" ");

export {
  list ,
  listA ,
  listB ,
  nestedList ,
  
}
/*  Not a pure module */
