// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as CamlinternalOO from "../node_modules/bs-platform/lib/es6/camlinternalOO.js";
import * as Caml_chrome_debugger from "../node_modules/bs-platform/lib/es6/caml_chrome_debugger.js";

var person = /* record */Caml_chrome_debugger.record([
    "name",
    "age"
  ], [
    "Adam",
    31
  ]);

function make(param) {
  return person;
}

function greet(details) {
  return "Hello. My name is " + (details[/* name */0] + (" and I am " + (String(details[/* age */1]) + " years old.")));
}

var Person = /* module */Caml_chrome_debugger.localModule([
    "person",
    "make",
    "greet"
  ], [
    person,
    make,
    greet
  ]);

(( console.clear() ));

console.warn("module");

console.warn(person);

console.log(" ");

var greet$1 = greet(person);

console.log("string");

console.log(greet$1);

console.log(" ");

var list = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    1,
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        2,
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            3,
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                4,
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    5,
                    /* [] */0
                  ])
              ])
          ])
      ])
  ]);

console.log("list (int)");

console.log(list);

console.log(" ");

var nestedList = /* :: */Caml_chrome_debugger.simpleVariant("::", [
    /* record */Caml_chrome_debugger.record([
        "name",
        "age"
      ], [
        "foo",
        23
      ]),
    /* :: */Caml_chrome_debugger.simpleVariant("::", [
        /* record */Caml_chrome_debugger.record([
            "name",
            "age"
          ], [
            "bar",
            28
          ]),
        /* :: */Caml_chrome_debugger.simpleVariant("::", [
            /* record */Caml_chrome_debugger.record([
                "name",
                "age"
              ], [
                "baz",
                14
              ]),
            /* :: */Caml_chrome_debugger.simpleVariant("::", [
                /* record */Caml_chrome_debugger.record([
                    "name",
                    "age"
                  ], [
                    "lors",
                    98
                  ]),
                /* :: */Caml_chrome_debugger.simpleVariant("::", [
                    /* record */Caml_chrome_debugger.record([
                        "name",
                        "age"
                      ], [
                        "crup",
                        11
                      ]),
                    /* [] */0
                  ])
              ])
          ])
      ])
  ]);

console.log("Record {name, age}");

console.log(List.hd(nestedList));

console.log(" ");

console.error("List (Person.details)");

console.error(nestedList);

console.log(" ");

var arr = /* array */[
  "a",
  "b",
  "c",
  "23"
];

console.log("array (string)");

console.log(arr);

console.log(" ");

var tuple = /* tuple */[
  1,
  2
];

console.error("(int, int)");

console.error(tuple);

console.log(" ");

var $$class = CamlinternalOO.create_table(["color"]);

var color = CamlinternalOO.get_method_label($$class, "color");

CamlinternalOO.set_method($$class, color, (function (self$1) {
        return "Red";
      }));

CamlinternalOO.init_class($$class);

var car = CamlinternalOO.create_object_opt(0, $$class);

console.error("Object");

console.error(car);

console.log(" ");

console.error("Variant");

console.error(/* PrettyMuch */2);

console.log(" ");

var adam = person;

var areYouCrushingIt = /* PrettyMuch */2;

export {
  Person ,
  adam ,
  greet$1 as greet,
  list ,
  nestedList ,
  arr ,
  tuple ,
  car ,
  areYouCrushingIt ,
  
}
/*  Not a pure module */
