// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Block from '../node_modules/bs-platform/lib/es6/block.js'
import * as CamlinternalOO from '../node_modules/bs-platform/lib/es6/camlinternalOO.js'

var person = /* record */ Block.record(['name', 'age'], ['Adam', 31])

function make(param) {
  return person
}

function greet(details) {
  return (
    'Hello. My name is ' +
    (details[/* name */ 0] +
      (' and I am ' + (String(details[/* age */ 1]) + ' years old.')))
  )
}

var Person = /* module */ Block.localModule(
  ['person', 'make', 'greet'],
  [person, make, greet]
)

console.log('module')

console.log(person)

console.log(' ')

var greet$1 = greet(person)

console.log('string')

console.log(greet$1)

console.log(' ')

var list = /* :: */ Block.simpleVariant('::', [
  1,
  /* :: */ Block.simpleVariant('::', [
    2,
    /* :: */ Block.simpleVariant('::', [
      3,
      /* :: */ Block.simpleVariant('::', [
        4,
        /* :: */ Block.simpleVariant('::', [5, /* [] */ 0])
      ])
    ])
  ])
])

console.log('list(int)')

console.log(list)

console.log(' ')

var nestedList = /* :: */ Block.simpleVariant('::', [
  /* record */ Block.record(['name', 'age'], ['foo', 23]),
  /* :: */ Block.simpleVariant('::', [
    /* record */ Block.record(['name', 'age'], ['bar', 28]),
    /* :: */ Block.simpleVariant('::', [
      /* record */ Block.record(['name', 'age'], ['baz', 14]),
      /* :: */ Block.simpleVariant('::', [
        /* record */ Block.record(['name', 'age'], ['lors', 98]),
        /* :: */ Block.simpleVariant('::', [
          /* record */ Block.record(['name', 'age'], ['crup', 11]),
          /* [] */ 0
        ])
      ])
    ])
  ])
])

console.log('list(Person.details)')

console.log(nestedList)

console.log(' ')

var arr = /* array */ ['a', 'b']

console.log('array(string)')

console.log(arr)

console.log(' ')

var tuple = /* tuple */ [1, 2]

console.log('(int, int)')

console.log(tuple)

console.log(' ')

var $$class = CamlinternalOO.create_table(['color'])

var color = CamlinternalOO.get_method_label($$class, 'color')

CamlinternalOO.set_method($$class, color, function(self$1) {
  return 'Red'
})

CamlinternalOO.init_class($$class)

var car = CamlinternalOO.create_object_opt(0, $$class)

console.log('record')

console.log(car)

console.log(' ')

console.log('Variant')

console.log(/* Yes */ 0)

console.log(' ')

var adam = person

var areYouCrushingIt = /* Yes */ 0

export {
  Person,
  adam,
  greet$1 as greet,
  list,
  nestedList,
  arr,
  tuple,
  car,
  areYouCrushingIt
}
/*  Not a pure module */
